In [ ]:
import pandas as pd
import numpy as np

In [ ]:
b1 = pd.read_csv("Main_Breaks_Post_March_2022.csv")
b2 = pd.read_csv("Main_Breaks_Jan_2013_to_March_2022.csv")
b3 = pd.read_csv("Main_Breaks_Pre_2013.csv")

In [ ]:
b1_clean = b1.rename(columns={
    "entityuid": "pipe_tag",
    "initiateda": "break_date"
})[["pipe_tag", "break_date"]]

b2_clean = b2.rename(columns={
    "pipe_tag": "pipe_tag",
    "date_repor": "break_date"
})[["pipe_tag", "break_date"]]

b3_clean = b3.rename(columns={
    "tag": "pipe_tag",
    "wodate": "break_date"
})[["pipe_tag", "break_date"]]

In [ ]:
b1_clean["break_date"] = pd.to_datetime(b1_clean["break_date"], errors="coerce")
b2_clean["break_date"] = pd.to_datetime(b2_clean["break_date"], errors="coerce")
b3_clean["break_date"] = pd.to_datetime(b3_clean["break_date"], errors="coerce")

/tmp/ipykernel_413/2467276329.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  b3_clean["break_date"] = pd.to_datetime(b3_clean["break_date"], errors="coerce")

In [ ]:
b1_clean.isna().sum()

pipe_tag      0
break_date    0
dtype: int64

In [ ]:
b2_clean.isna().sum()

pipe_tag      0
break_date    0
dtype: int64

In [ ]:
b3_clean.isna().sum()

pipe_tag       0
break_date    67
dtype: int64

In [ ]:
b3_clean = b3_clean.dropna()

In [ ]:
b3_clean.isna().sum()

pipe_tag      0
break_date    0
dtype: int64

In [ ]:
breaks1 = pd.concat([b1_clean, b2_clean], ignore_index=True)

In [ ]:
breaks2 = pd.concat([b1_clean, b2_clean, b3_clean], ignore_index=True)

In [ ]:
breaks1.head()

  pipe_tag break_date
0    wp526 2022-08-10
1    p3844 2022-08-12
2    p3978 2022-08-19
3  wp37055 2022-08-22
4  wp15798 2022-08-22

In [ ]:
breaks2.tail()

       pipe_tag break_date
2222  wpbrk0524 1985-10-15
2223  wpbrk0641 1983-01-03
2224  wpbrk0922 2001-01-08
2225  wpbrk0204 1991-12-20
2226  wpbrk0080 1994-01-07

In [ ]:
breaks1.to_csv("Breaks2013toNow.csv", index=False)

In [ ]:
breaks2.to_csv("BreaksWithHistorical.csv", index=False)

In [ ]:
len(breaks1)

960

In [ ]:
len(breaks2)

2227